{%- from "reclass/map.jinja" import storage with context %}
storage_type: {{ storage.storage_type }}
pretty_print: True
output: {{ storage.get('output', 'json') }}
inventory_base_uri: {{ storage.base_dir }}
{%- if storage.nodes_uri is defined %}
nodes_uri: {{ storage.nodes_uri }}
{%- endif %}
{%- if storage.reclass_source_path is defined %}
reclass_source_path: {{ storage.reclass_source_path }}
{%- endif %}
{%- if storage.class_mappings|length > 0 %}
class_mappings:
{%- for mapping in storage.class_mappings %}
- {{ mapping.target }} {{ mapping.class }}
{%- endfor %}
{%- endif %}
{%- if storage.propagate_pillar_data_to_reclass == True %}
propagate_pillar_data_to_reclass: {{ storage.propagate_pillar_data_to_reclass }}
{%- endif %}
# Below option are not available in original reclass,
# use fork with extensions from https://github.com/salt-formulas/reclass
{%- if storage.ignore_class_notfound == True %}
ignore_class_notfound: {{ storage.ignore_class_notfound }}
{%- endif %}
{%- if storage.allow_scalar_over_dict is defined %}
allow_scalar_over_dict: {{ storage.allow_scalar_over_dict }}
{%- endif %}
{%- if storage.allow_scalar_over_list is defined %}
allow_scalar_over_list: {{ storage.allow_scalar_over_list }}
{%- endif %}
{%- if storage.allow_list_over_scalar is defined %}
allow_list_over_scalar: {{ storage.allow_list_over_scalar }}
{%- endif %}
{%- if storage.allow_dict_over_scalar is defined %}
allow_dict_over_scalar: {{ storage.allow_dict_over_scalar }}
{%- endif %}
{%- if storage.allow_none_override is defined %}
allow_none_override: {{ storage.allow_none_override }}
{%- endif %}
